<?php

namespace AppBundle\Repository;

/**
 * BlogUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogUserRepository extends \Doctrine\ORM\EntityRepository
{
}
